### PR TITLE
feat: re-order top nav items

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Updates all product-specific top navs with a consistent link order. Specifically, links are always shown in the following order:

- Install
- Intro (a documentation category, currently only used by Nomad & Vagrant)
- Tutorials
- Documentation Categories (except Intro). In the specific order: Docs, API, CLI, Tools, Plugins
- Cloud

> **Note**: All products should have top nav links that match the following order (with only certain links visible on certain products, but order the same regardless of which links are visible).

## 🛠️ How

- Updates `get-nav-items` function that powers all top navs, to match the above specific order
- Also updates related test snapshots

## 🎨 Design Screenshots

| Product | Before | After |
| - | - | - |
| [/terraform][/terraform] | Screen Shot 2023-01-25 at 13 56 58 | Screen Shot 2023-01-25 at 13 52 20 | 
| [/packer][/packer] | Screen Shot 2023-01-25 at 13 57 08 | Screen Shot 2023-01-25 at 13 52 28 |
| [/consul][/consul] | Screen Shot 2023-01-25 at 13 57 11 | Screen Shot 2023-01-25 at 13 52 36 |
| [/vault][/vault] | Screen Shot 2023-01-25 at 13 57 14 | Screen Shot 2023-01-25 at 13 54 25 |
| [/boundary][/boundary] | Screen Shot 2023-01-25 at 13 57 22 | Screen Shot 2023-01-25 at 13 52 56 |
| [/nomad][/nomad] | Screen Shot 2023-01-25 at 13 57 24 | Screen Shot 2023-01-25 at 13 53 00 |
| [/waypoint][/waypoint] | Screen Shot 2023-01-25 at 13 57 34 | Screen Shot 2023-01-25 at 13 53 05 |
| [/vagrant][/vagrant] | Screen Shot 2023-01-25 at 13 57 30 | Screen Shot 2023-01-25 at 13 53 17 |

## 🧪 Testing

- [ ] Visit a page within each product context, and compare to upstream
    - For example, compare [/nomad][/nomad] to [upstream][upstream/nomad]
    - The top nav within each product context should have the same links as previously
    - The order of links within the top nav should be consistent across products

## 💭 Anything else?

We have implicit approval from Geoffrey and Mike on this change, see comments on 🎟️ [the Asana task][task].

[task]: https://app.asana.com/0/1203461693655903/1203752518527710/f
[preview]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/
[/terraform]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/terraform
[/packer]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/packer
[/consul]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/consul
[/vault]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/vault
[/boundary]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/boundary
[/nomad]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/nomad
[/waypoint]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/waypoint
[/vagrant]: https://dev-portal-git-zstop-nav-consistent-order-hashicorp.vercel.app/vagrant
[upstream/nomad]: https://developer.hashicorp.com/nomad

### CODE REVIEW

**Review by kendallstrautman — APPROVED** [review]
👏🏻 LGTM!

**Comment by ashleemboyer** [comment]
@zchsh should Intro come before Tutorials on `/nomad` since that's a section of docs? I was expecting it to come after the Documentation nav item like other docs sections do.

**Review by ashleemboyer — APPROVED** [review]

**Comment by zchsh** [comment]
@ashleemboyer Ah, I could have linked this more clearly - Geoffrey mentioned this in [a comment on a previous Asana task](https://app.asana.com/0/0/1203524858954780/1203768154771093/f) - it seems like education specifically wants `Intro` to be split out and listed earlier in the nav when it's present (ie for Nomad and Vagrant). There's [a later comment](https://app.asana.com/0/0/1203752518527710/1203778126712174/f) where he confirms this is what they're looking for (and acknowledges we'll likely adjust this in the future, either by adding Intro content for other products, or removing it for Nomad & Vagrant).

**Review by heitzke — COMMENTED** [review]
Looks good to me 👍

**Pull request merged**
