### PR TITLE
fix(homepage): badge asset quality

### PR DESCRIPTION
**Pull request by alexcarpenter**
## "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [x] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [x] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-achomepagefix-badge-asset-hashicorp.vercel.app/) 🔎
- [Slack thread](https://hashicorp.slack.com/archives/C03B1KDDATV/p1650063782227959?thread_ts=1650037781.870159&cid=C03B1KDDATV) 🎟️

## What

The learn section badge asset was rendering blurry in Safari. This PR updates the asset to be a 2x png to fix the issue.

CleanShot 2022-04-18 at 16 45 41@2x

Before: https://dev-portal-git-achomepagepolish-hashicorp.vercel.app
After: https://dev-portal-git-achomepagefix-badge-asset-hashicorp.vercel.app

## How

Convert asset from SVG to 2x PNG

## Testing

- [ ] Open new homepage in Safari
- [ ] Learn search badge should be crisp

### CODE REVIEW

**Comment by BRKalow** [comment]
It's blurry in chrome for me now 😢

**Comment by BRKalow** [comment]
I'm not on a retina display (looking on my external monitor), but on safari desktop the SVG still looks crisper. 🤷‍♂️

**Comment by alexcarpenter** [comment]
Something is up with using the SVG within next/image. Dropping the SVG directly on the page renders sharp. 🤔

**Comment by alexcarpenter** [comment]
@BRKalow Opted to make use of InlineSvg for now.

**Review by BRKalow — APPROVED** [review]

**Pull request merged**
