### PR TITLE
updated certification images on homepage and landing

### PR DESCRIPTION
**Pull request by anthonyvetter**
## 🔗 Relevant links

- [Preview link home page](https://dev-portal-git-tvupdate-certification-images-hashicorp.vercel.app/) 🔎
- [Preview link certifications](https://dev-portal-git-tvupdate-certification-images-hashicorp.vercel.app/certifications) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1205161599037038/f) 🎟️

## 🗒️ What

Updated certification images on the home page `/` and certification landing `/certifications` 

## 🤷 Why

Terraform launched Associate 003, and that needed to be reflected in the images.

## 🛠️ How

Deleted the old images, named the new images the same as the old, and copied the new images in. 
Verified locally and checked with Design to confirm the new image size was intentional. 

## 🧪 Testing

- [ ] visit the home page 
  - ensure the image is loading and looks right
- [ ] visit `/certifications` 
  - ensure the hero is loading and looks right

## 💭 Anything else?

First PR 🎉 . Feedback welcome. But just make sure I am not about to break anything ;)

### CODE REVIEW

**Comment by kendallstrautman** [comment]
@anthonyvetter can you sign the CLA?

**Review by kendallstrautman — CHANGES_REQUESTED** [review]
It looks like the aspect ratios for these images changed [from upstream](https://developer.hashicorp.com/certifications), causing them to render differently. The homepage one isn't right. cc @kellyschummer 👀

**Comment by kendallstrautman** [comment]
Oh @anthonyvetter I think its because we need to update the dimensions on the image component itself. [See homepage](https://github.com/hashicorp/dev-portal/blob/main/src/views/homepage/components/featured-content-grid/certifications-featured-card.tsx#L27-L28) and [cert page](https://github.com/hashicorp/dev-portal/blob/main/src/views/certifications/views/landing/components/landing-hero/index.tsx#L33)

**Comment by kaitlynnefuery** [comment]
Recap of Slack convo: @anthonyvetter has signed the CLA with an email that matches his GitHub account, but it still isn't registering it's been signed. Seems like the same problem others have where we need to trigger the CLA assistant to run again w/ him committing again or via admin: https://github.com/cla-assistant/cla-assistant/issues/295#issuecomment-349387216

**Review by kendallstrautman — APPROVED** [review]

**Comment by anthonyvetter** [comment]
@kendallstrautman, Tracked down the CLA issue. The PR was opened somehow (very much on my end) with the wrong email address which was not associated with my GitHub account. I fixed the issue so `anthonyvetter` has signed the CLA, but the opener of the PR, Antony Vetter, has not. If you want me to delete and resubmit I can do that. 

On the SVGs, I have worked with @kellyschummer and @kaitlynnefuery on the resizing. The aspect ratio issue seems to be fixed but the homepage image remains a different size. We aren't sure how to fix that, or even really why it is happening. 

I have shown the preview to @kellyschummer, including a comparison to prod and she is fine with the change. Just being overly verbose here. We are fine merging these changes but wanted to highlight the story.

**Pull request merged**
