### PR TITLE
chore(hcp callout): update graphic for infrastructure solution group

### PR DESCRIPTION
**Pull request by pbortnick**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-pbupdate-infrastructure-graphic-hashicorp.vercel.app/swingset/components/mdxhcpcallout) 🔎
- [Asana task](url) 🎟️

## 🗒️ What

Update graphic as per design request.

### CODE REVIEW

**Comment by BRKalow** [comment]
@pbortnick can we [squoosh](https://squoosh.app/) this? It looks like the image is almost identical, but it went up ~4x in file size

**Comment by pbortnick** [comment]
> @pbortnick can we [squoosh](https://squoosh.app/) this? It looks like the image is almost identical, but it went up ~4x in file size

@kellyschummer is there much of a difference in the preview that we need this?

**Comment by pbortnick** [comment]
@BRKalow I ran the image through an optimizer to decrease the file size diff

**Comment by pbortnick** [comment]
@BRKalow ran the image through an optimizer. Seems like the diff decreased

**Review by BRKalow — APPROVED** [review]

**Pull request merged**
