### PR TITLE
[Global Search] Final polish ✨ 

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🗒️ What

- Updates `tabsWrapper` `padding-bottom` to `16px`
- Updates mobile rendering of the Tutorial Library CTA (shows at bottom of Tutorials tab)
- Shortens `<input />` placeholder text for HCP, for improved mobile rendering
- Adds custom icon for the cmd/ctrl `Badge` in `CommandBarActivator` and `CommandBarDialogHeader`
  - Also updates the `ariaLabel` for this `Badge` to be accurate
- Adds `preventDefault` in the cmd/ctrl + k listener

## 📸 Design Screenshots

[Tutorial Library CTA](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=14878%3A187982&viewport=-7005%2C-18321%2C1.33)

image

[CommandBarActivator Badge](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=14911%3A186799&viewport=-32162%2C9252%2C3.77)

image

CommandBarDialogHeader Badge

image

## 🧪 Testing

Go to [the preview URL](https://dev-portal-git-ambglobal-search-final-polish-hashicorp.vercel.app/) and make sure the updates listed above are as expected.

### CODE REVIEW

**Comment by BRKalow** [comment]
@ashleemboyer do we want to update this icon too? 💭 

Screen Shot 2022-09-30 at 12 59 47 PM

**Comment by ashleemboyer** [comment]
> @ashleemboyer do we want to update this icon too? 💭
> 
> Screen Shot 2022-09-30 at 12 59 47 PM

@BRKalow ahhh yes! We do. Great catch 👀

**Review by braydenlove — COMMENTED** [review]
Awesome work on those changes @ashleemboyer. Do you want me to approve these now and wait to confirm that we have the hotkeys working on Windows/Linux? Or just wait for it all in one super PR? Based on your title I think we wait, we will sync on Monday.

**Comment by kellyschummer** [comment]
🥳 this is looking great! Thank you @ashleemboyer - Let me know if you need another svg for the inline placement. 💯

**Comment by ashleemboyer** [comment]
> > @ashleemboyer do we want to update this icon too? 💭
> > Screen Shot 2022-09-30 at 12 59 47 PM
> 
> @BRKalow ahhh yes! We do. Great catch 👀

@BRKalow this is resolved in https://github.com/hashicorp/dev-portal/pull/1136/commits/e21524eec75d8a2e3fc45d655d3f53344e0e119a!

**Review by BRKalow — APPROVED** [review]
👏

**Comment by braydenlove** [comment]
One thing I noticed @ashleemboyer is that the top nav is getting cut off on HCP at 320 (our smallest size we support). This might be related to switching out the full size HCP logo to the smaller mobile one but I am not sure if that work has been done yet. I still can't upload images so I will DM you a screenshot CC @kellyschummer

**Comment by ashleemboyer** [comment]
> One thing I noticed @ashleemboyer is that the top nav is getting cut off on HCP at 320 (our smallest size we support). This might be related to switching out the full size HCP logo to the smaller mobile one but I am not sure if that work has been done yet. I still can't upload images so I will DM you a screenshot CC @kellyschummer

@braydenlove this should now be resolved in https://github.com/hashicorp/dev-portal/pull/1136/commits/08997a95cb4ecc8b3a1c33ee26db4250920e19c4! The build will finish shortly 😊

**Review by braydenlove — APPROVED** [review]
Looks awesome, APPROVED!!!!!

**Pull request merged**
