### PR TITLE
Assembly - UI V1

### PR DESCRIPTION
**Pull request by ashleemboyer**
This assembly contains all of the work on the new Dev Dot UI since October 2021.

👀  [Preview](https://dev-portal-git-assembly-ui-v1-hashicorp.vercel.app)

### CODE REVIEW

**Comment by ashleemboyer** [comment]
Pushed a hotfix this morning for cards: https://github.com/hashicorp/dev-portal/pull/22/commits/c7d340689d35a9179ecad8a79f41931c756c55c1. One of my last commits on #83 fixed some too-wide anchor elements in swingset but broke all the cards in the site and I didn't notice! To fix in swingset, I'm adding some inline styles in #88 in https://github.com/hashicorp/dev-portal/pull/88/commits/9deac7d103480d23cc03abfd5338db0c403287bd. 🌸

**Comment by ashleemboyer** [comment]
What's in this branch was thoroughly tested in #175. @BRKalow and I will be collabing on getting this branch merged tomorrow morning! 🎉

**Comment by ashleemboyer** [comment]
Latest commit adds a README for the `src/data` file, which accomplishes the proposal I needed to write for: https://app.asana.com/0/1201010428539925/1201803296751794/f.

**Review by BRKalow — APPROVED** [review]
:shipit:

**Pull request merged**
