### PR TITLE
feat: tweak collection progress group appearance

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Tweaks Collection Progress Group appearance to match recent revisions.

This change could be summarized as:
- Unauthenticated users now have a tweaked appearance for collection progress elements, with a light gray background
- ~Authenticated users will now always see the `x/x tutorials` + progress bar for collection progress elements~
    - We've since reverted this change, behaviour is the same as before

## 🤷 Why

To address VQA-oriented feedback and improvements on User Progress features.

## 🛠️ How

- chore: update height in sidebar to 36px
- feat: update collection-progress-status-seciton bg
- chore: update use of collection-progress-status-section
- ~feat: update collection-card progress to match~

## 📸 Design Screenshots

🎨 [Figma spec][figma]

### Collection progress in sidebar

---

##### Before

sidebar-unauth-before

##### After

sidebar-unauth-after

### Collection progress in Collection meta

---

##### Before

meta-unauth-before

##### After

meta-unauth-after

## 🧪 Testing

- [ ] Confirm that Collection Progress in sidebar is updated as expected
    - Visit a tutorial page, such as [/consul/tutorials/get-started-hcp/hcp-gs-deploy][/consul/tutorials/get-started-hcp/hcp-gs-deploy]
    - When unauthenticated, the sidebar should show the collection progress element with `x tutorials` and a very light gray background.
- [ ] Confirm that Collection Meta progress display is updated as expected
    - Visit a collection view, such as [/consul/tutorials/get-started-hcp][/consul/tutorials/get-started-hcp]
    - When unauthenticated, the progress section should show the collection progress element with `x tutorials` and a very light gray background.

## 💭 Anything else?

Not at the moment!

[preview]: https://dev-portal-git-zstweak-collection-progress-group-hashicorp.vercel.app
[task]: https://app.asana.com/0/1202097197789424/1203111459158271/f
[figma]: https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=15065%3A191390
[/consul]: https://dev-portal-git-zstweak-collection-progress-group-hashicorp.vercel.app/consul
[/consul/tutorials/get-started-hcp/hcp-gs-deploy]: https://dev-portal-git-zstweak-collection-progress-group-hashicorp.vercel.app/consul/tutorials/get-started-hcp/hcp-gs-deploy
[/consul/tutorials/get-started-hcp]: https://dev-portal-git-zstweak-collection-progress-group-hashicorp.vercel.app/consul/tutorials/get-started-hcp

### CODE REVIEW

**Comment by zchsh** [comment]
@braydenlove @BRKalow This PR tweaks the appearance of collection progress items to match recently updated post-VQA changes. Let me know what y'all think 🙇‍♂️ 💖

**Comment by braydenlove** [comment]
This is great, the only thing we missed is to not show progress on the cards until you have visited the collection or a tutorial within the collection. LMK if this is tricky or if you have any questions!

**Comment by braydenlove** [comment]
If possible it would be awesome to show no progress for authed users until they land on either 1. The collection page or 2. a tutorial within a collection. Once the user lands one of those pages we would show 0/XX as they have arrived there but haven't made progress yet. If this is too in the weeds maybe we just back out and look at it again when we have more time.

**Comment by zchsh** [comment]
@braydenlove ah yeah, changing the behaviour of the component based on recent authenticated page views sounds like it could get complex. Or at least, seems like it would be well outside the scope of VQA'ing the implementation of the existing design specs.

I think in the scope of this PR, we need to make a call on when `xx tutorials` vs `0/xx tutorials + progress bar` is shown. The rough options I have in my head:
1. Consistently show based on authenticated state
`xx tutorials` is shown to unauthenticated visitors.  `0/xx tutorials` is shown to authenticated visitors.

**Comment by braydenlove** [comment]
@zchsh let's go with 2 and we can follow up as needed in the future to dig in deeper.

**Comment by zchsh** [comment]
@braydenlove Sounds good!

The only thing I can think of there is then the logic for the gray background might need to change as well. Should we:
1. Show gray background to unauthenticated users, show white background to authenticated users
    - This would mean background color would change based on authentication; but the `xx tutorials` vs `0/xx tutorials` would change based on progress.
    - So we'd sometimes see `xx tutorials` with a gray background (unauthenticated users), and sometimes we'd see `xx tutorials` with a white background (authenticated users with no progress). (`0/xx tutorials` with the progress bar would always have a white background, of course).
2. Show gray background with `xx tutorials`, show white background with `0/xx tutorials`
    - aka base the background on collection progress, not directly on authentication
    - might be more consistent from a design perspective?

Let me know what you think, or if there's anything I can clarify there (I worry that's not super clear ha 😅 )

**Comment by braydenlove** [comment]
I think 2 makes the most sense right?

**Comment by zchsh** [comment]
@braydenlove Sweet! I think so too (weak opinion though haha), will be a slight tweak! Will make those tweaks shortly (grabbing lunch first) and then should be ready for final review 👍

**Comment by braydenlove** [comment]
@zchsh see my new comment, might be worth jumping on a 5 min zoom?

**Review by braydenlove — APPROVED** [review]
Looks good on zoom, un-auth looks great in browser. Ship it!

**Review by BRKalow — APPROVED** [review]
lgtm!

**Pull request merged**
