### PR TITLE
chore: update form tokens

### PR DESCRIPTION
**Pull request by kendallstrautman**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ksupdate-form-tokens-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1204108584803973) 🎟️

## 🗒️ What

This PR tweaks the form token values as defined[ in this ticket](https://app.asana.com/0/1199634971449915/1204108584803973). The hex values have been mapped to their core palette tokens. 

## 🧪 Testing

- [Visit a tutorial page](https://dev-portal-git-ksupdate-form-tokens-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro), scroll down to view the feedback form. Validate that it looks okay. Also validate that the values are mapped properlty @braydenlove

### CODE REVIEW

**Review by zchsh — APPROVED** [review]
✅ Checked out the buttons on [the preview](https://dev-portal-git-ksupdate-form-tokens-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro), looks good to me!

**Comment by kendallstrautman** [comment]
@braydenlove the textarea color looks a little light to me. Thoughts?

Screenshot 2023-03-16 at 9 25 16 AM

**Comment by braydenlove** [comment]
@kendallstrautman the bg of text fields should be  `--token-form-control-base-surface-color-default`

Here is an example of the change in inspect
image

**Comment by kendallstrautman** [comment]
@braydenlove just made that update, looks much better 💯 Lmk what you think

**Review by braydenlove — APPROVED** [review]
A W E S O M E

**Pull request merged**
