### PR TITLE
Making Sidebar collapsible/expandable

### PR DESCRIPTION
**Pull request by ashleemboyer**
## ✅ "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The description template has been filled in below

---

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ambcollapse-sidebar-v2-hashicorp.vercel.app/) 🔎

## 🗒️ What/Why

- Updates `SidebarNavDataContext` to hold and manage the open/closed state of `Sidebar`, since that `Context` holds other relevant data for `Sidebar`.
- Updates `NavigationHeader` to hide nav content and show a menu button (for changing the open/closed state of `Sidebar`) starting at `1000px`.
- Adds `--dev-dot-tablet-down` custom media for applying styles in various CSS sheets when some items start to hide and change the flow of different parts of the page.

## 🧪 Testing

- [ ] Go to [the home page](https://dev-portal-git-ambcollapse-sidebar-v2-hashicorp.vercel.app/)
- [ ] It should load without error
- [ ] Change the viewport to `1000px` or less
- [ ] The primary nav content should go away
- [ ] No menu button should appear
- [ ] Go to [/waypoint](https://dev-portal-git-ambcollapse-sidebar-v2-hashicorp.vercel.app/waypoint)
- [ ] Make sure you can open/close the `Sidebar` starting at `1000px` and lower
- [ ] Make sure the `Sidebar` collapses if a link menu item has been selected
- [ ] Go to [/waypoint/docs](https://dev-portal-git-ambcollapse-sidebar-v2-hashicorp.vercel.app/waypoint/docs)
- [ ] Make your viewport `1000px` or less
- [ ] Open the `Sidebar`
- [ ] "Waypoint Home" should be a button
- [ ] Click it
- [ ] The `Sidebar` should stay open
- [ ] You should see menu items that match /waypoint sidebar data
- [ ] You should see "Main Menu" and "Previous" buttons at the top of the `Sidebar`
- [ ] Continue interacting with the `Sidebar` buttons and make sure they behave as you expect
- [ ] Make your viewport `1000px` or less
- [ ] Open the `Sidebar`
- [ ] Resize your viewport to be smaller
- [ ] The `Sidebar` should not collapse
- [ ] Resize your viewport to be greater than `1000px`
- [ ] The `Sidebar` should collapse

## 💭 Anything else?

- This doesn't add a menu on mobile on the home page. I'm not sure yet what that looks like since that page doesn't use `SidebarSidecarLayout`, so I'm not sure if that's too large to figure out in this PR or not. Maybe we don't hide the home page nav on mobile yet?
- The items within the `Sidebar` are still focusable when it's collapsed. I can't for the life of me remember how to address this, please halp! 🙏🏻

### CODE REVIEW

**Comment by BRKalow** [comment]
Quick observation: If i navigate from the homepage to a product homepage, the nav is opened:

Screen Shot 2022-04-22 at 9 47 18 AM

**Comment by ashleemboyer** [comment]
> Quick observation: If i navigate from the homepage to a product homepage, the nav is opened:

Wow, that's weird 🤔

**Comment by ashleemboyer** [comment]
@BRKalow that issue should be fixed with https://github.com/hashicorp/dev-portal/pull/364/commits/f7c597c8f50d1ff987bdccf5f867c15998893e8f!

**Comment by BRKalow** [comment]
Some thoughts:
* should we make the main content area hidden from assistive technology while the menu is open?
* We should restrict scrolling while the menu is open so you can't "scroll past" the full screen menu.
  * There are a few ways to accomplish this, here's a quick and dirty example which retains the scrollbar to avoid horizontal layout shift (see styles set on body and the layout root element):
Screen Shot 2022-04-22 at 10 03 21 AM

**Comment by ashleemboyer** [comment]
@BRKalow @alexcarpenter added framer-motion for animating the Sidebar open/closed, also have it respecting prefers-reduced-motion!

- Not sure yet how to "hide" the main content area except to close the Sidebar when focus leaves the element.
- Also not sure yet how to address the scrolling issue, like where in the code I should be trying to address it. 🤔

**Comment by ashleemboyer** [comment]
@BRKalow @alexcarpenter apologies for the double tag! Just added a couple more things:

- Sidebar closes on mobile now if focus moves outside of its `div`
- Added a missing `aria-label` for the menu button

Is it possible to move forward without fixing the scrolling issue yet? Maybe someone else already has a good idea of how to fix that, and it can be addressed in a separate PR?

**Review by zchsh — APPROVED** [review]
📊 🎉 Followed the testing steps & looks good to me 👍

**Pull request merged**
