### PR TITLE
feat(downloads): derive the latest version from the fetched releases data

### PR DESCRIPTION
**Pull request by BRKalow**
## "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [x] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-brkfeat-downloads-derive-latest-84be77-hashicorp.vercel.app) 🔎
- [Asana task](https://app.asana.com/0/1201010428539925/1201722975655666/f) 🎟️

## What

Derive `latestVersion` from the data fetched from releases.hashicorp.com

## Why

In order to reduce the reliance on manually bumping a version for a product release, we want to derive it automatically.

## How

I copy-pasted the downloads page server code and made some adjustments

## Testing

- [ ] Navigate to https://dev-portal-git-brkfeat-downloads-derive-latest-84be77-hashicorp.vercel.app
- [ ] Select waypoint in the product switcher in the bottom left
- [ ] Navigate to the downloads page
- [ ] Validate that the latest version says `0.7.1`

### CODE REVIEW

**Review by thiskevinwang — APPROVED** [review]
LGTM!

**Comment by thiskevinwang** [comment]
I'm not sure if this is related, but Sentinel downloads looks off
- https://dev-portal-git-brkfeat-downloads-derive-latest-84be77-hashicorp.vercel.app/sentinel/downloads

**Comment by BRKalow** [comment]
@thiskevinwang ooh good eye! This only touches WP but I'll take a look at sentinel as a follow up 🙇

**Comment by thiskevinwang** [comment]
Ok, it's not related to this PR 👍 

I just checked https://test-bd.hashi-mktg.com/downloads, which also looks to have this bug
image

**Comment by BRKalow** [comment]
@thiskevinwang yeah I think it's cause the versions we have statically declared here are not the actual latest. This change would fix those products too 😄

**Pull request merged**
