### PR TITLE
Adding Try Cloud item for products in hcp

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/0/1203333219291187/f) 🎟️

## 🗒️ What

- Adds "Try Cloud" nav header link for Boundary, Consul, HCP, Packer, Terraform, Vault, and Waypoint

## 📸 Design Screenshots

[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=15473%3A197055&viewport=2885%2C2786%2C0.91&t=wUhUXlNWrGtQjWm7-11)

image

## 🧪 Testing

- [ ] Make sure the new CTA shows for pages under [/boundary](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/boundary)
- [ ] Make sure the new CTA shows for pages under [/consul](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/consul)
- [ ] Make sure the new CTA shows for pages under [/hcp](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/hcp)
- [ ] Make sure the new CTA shows for pages under [/packer](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/packer)
- [ ] Make sure the new CTA shows for pages under [/terraform](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/terraform)
- [ ] Make sure the new CTA shows for pages under [/vault](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/vault)
- [ ] Make sure the new CTA shows for pages under [/waypoint](https://dev-portal-git-ambtry-cloud-nav-link-hashicorp.vercel.app/waypoint)

### CODE REVIEW

**Comment by kylemac** [comment]
added @BRKalow for review bc he has context about the product_intent handler that exists already

**Review by zchsh — APPROVED** [review]
✅ looks good to me - I tested out each of the links 🔗 

For Terraform, I end up seeing the link as `https://app.terraform.io/public/signup/account?product_intent=terraform` 🤔 I think `?product_intent` must be added on outside of `dev-portal`? Figured this is fine, and it seems clear it's not here in `dev-portal` that we're adding it, but wanted to flag just in case 👍

EDIT: oops, just saw Kyle's comment above! I too am curious about the `product_intent` handler.

**Review by emilypersson1 — APPROVED** [review]
Working how I'd expect. Thanks Ashlee!

**Comment by alexcarpenter** [comment]
> ✅ looks good to me - I tested out each of the links 🔗
> 
> For Terraform, I end up seeing the link as `https://app.terraform.io/public/signup/account?product_intent=terraform` 🤔 I think `?product_intent` must be added on outside of `dev-portal`? Figured this is fine, and it seems clear it's not here in `dev-portal` that we're adding it, but wanted to flag just in case 👍
> 
> EDIT: oops, just saw Kyle's comment above! I too am curious about the `product_intent` handler.

Links that currently go to app.terraform.io and portal.cloud.hashicorp.com get product intent param added to the URL. https://github.com/hashicorp/web-platform-packages/blob/main/packages/analytics/add-cloud-link-handler/index.ts#L29-L31

We get the product intent simply from the URL https://github.com/hashicorp/web-platform-packages/blob/main/packages/analytics/get-product-intent-from-url/index.ts

**Comment by alexcarpenter** [comment]
> > > ✅ looks good to me - I tested out each of the links 🔗
> > > For Terraform, I end up seeing the link as `https://app.terraform.io/public/signup/account?product_intent=terraform` 🤔 I think `?product_intent` must be added on outside of `dev-portal`? Figured this is fine, and it seems clear it's not here in `dev-portal` that we're adding it, but wanted to flag just in case 👍
> > > EDIT: oops, just saw Kyle's comment above! I too am curious about the `product_intent` handler.
> > 
> > 
> > Links that currently go to app.terraform.io and portal.cloud.hashicorp.com get product intent param added to the URL. https://github.com/hashicorp/web-platform-packages/blob/main/packages/analytics/add-cloud-link-handler/index.ts#L29-L31
> > We get the product intent simply from the URL https://github.com/hashicorp/web-platform-packages/blob/main/packages/analytics/get-product-intent-from-url/index.ts
> 
> @alexcarpenter does this mean we don't need to manually set the `product_intent` param when creating the link?

That is correct.

**Comment by ashleemboyer** [comment]
> 

@alexcarpenter nice! Removed in https://github.com/hashicorp/dev-portal/pull/1341/commits/8876b119da1862037cdf28db7a5a066add446834 ✅

**Pull request merged**
