### PR TITLE
feat(homepage): add `HeroWithActions` and `HeroWithVideo` exports

### PR DESCRIPTION
**Pull request by alexcarpenter**
## "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [x] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [x] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-achomepagehero-video-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/inbox/1200641486636491/1202156824097068/1202156841662051) 🎟️

## What

Introduces `HeroWithVideo` and `HeroWithActions` options for homepage implementation needs. Instead of create a monolith hero component that accepts a multitude of props, create smaller exports for either needs. 

**HeroWithVideo:**

CleanShot 2022-04-20 at 16 05 35@2x

**HeroWithActions:**

CleanShot 2022-04-20 at 16 07 32@2x

## Why

Homepage hero needed video option for launch.

## How

Split hero up into smaller withVideo and withActions components.

### CODE REVIEW

**Comment by alexcarpenter** [comment]
@BrandonRomano Dropped a youtube video for now. Do you have a link to the final video on wistia by chance?

**Comment by BrandonRomano** [comment]
Nope I don't -- also I don't think we will until we are basically at code-freeze for our initial release; @topfunky is going to make us a video once we have the site all put together and he'll walk through it.

So the temporary video for now is a good call 👍

**Review by BrandonRomano — APPROVED** [review]
This looks good!  Thanks @alexcarpenter

**Review by zchsh — APPROVED** [review]
✅ Looks great to me 💯

**Pull request merged**
