### PR TITLE
[Tabs] Add "compact" variant

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ambcompact-tabs-hashicorp.vercel.app/swingset/components/tabs) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1203040536543890/f) 🎟️

## 🗒️ What

- Adds `variant` prop to `Tabs` with two options: `"normal"` (default) and `"compact"`

## 🤷 Why

- These changes make it possible to get the tabs styles needed for Global Search without affecting existing usage of Tabs in MDX content and install views

## 📸 Design Screenshots

[HDS Figma Link](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/HDS-Product---Components?node-id=16384%3A46484&viewport=519%2C394%2C0.62)

image

[Dev Dot Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12357%3A141909&viewport=-26591%2C6060%2C4.79)

image

## 🧪 Testing

- [ ] Go to [the Tabs Swingset page](https://dev-portal-git-ambcompact-tabs-hashicorp.vercel.app/swingset/components/tabs)
- [ ] Scroll to the new example
- [ ] Make sure the component renders as you expect

### CODE REVIEW

**Comment by BRKalow** [comment]
@ashleemboyer (minor) The focus ring looks a little funny, do you think we want it to also include the icon?
Screen Shot 2022-09-26 at 11 03 03 AM

**Comment by ashleemboyer** [comment]
> @ashleemboyer (minor) The focus ring looks a little funny, do you think we want it to also include the icon? Screen Shot 2022-09-26 at 11 03 03 AM

Ahhhh yeah that's not right. Fixing!

**Comment by ashleemboyer** [comment]
> > @ashleemboyer (minor) The focus ring looks a little funny, do you think we want it to also include the icon? Screen Shot 2022-09-26 at 11 03 03 AM
> 
> Ahhhh yeah that's not right. Fixing!

@BRKalow fixed in https://github.com/hashicorp/dev-portal/pull/1082/commits/2cdf9589a7226d789a571c68fbc7d893e10b8eea!

**Review by BRKalow — APPROVED** [review]
👍 looks great!

**Pull request merged**
