### PR TITLE
fix: issue with toast route change detection

### PR DESCRIPTION
**Pull request by zchsh**
## ✅ "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [x] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [x] The description template has been filled in below

---

## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202332432700512/f) 🎟️

## 🗒️ What

Ensures a welcome toast shows up when opting in to the dev-portal beta from docs sites.

## 🤷 Why

To display a welcome toast to visitors when they opt-in to the dev-portal beta. Specifically, ensure this toast appears when coming from docs sites.

## 🛠️ How

Replaces the existing `useEffect` which relied on `routeChangeComplete` with a new hook that relies on `router.asPath`. 

Monitoring the URL in this way seems to give a more accurate reflection of when the URL changes from the initial `router.asPath` to a new `router.asPath`. With `routeChangeComplete`, this detection did not seem to work as expected, and the toast would auto-dismiss as soon as the page mounted, resulting in the experience of not seeing the toast at all.

## 📸 Design Screenshots

CleanShot 2022-05-30 at 11 32 40@2x

## 🧪 Testing

- [ ] Visit a docs page with an `optInFrom` parameter, such as [/waypoint/docs?optInFrom=waypoint-io][preview]
    - A welcome toast should appear in the lower left of the viewport, and be announced as an `aria-live="polite"` region
    - The welcome toast should auto-dismiss after 15 seconds
    - The welcome toast should be able to be manually dismissed with the `×` button
    - The `Leave Beta` button should appear at the top right of the main content area

## 💭 Anything else?

Not at the moment! Note that similar toasts for tutorials opt-ins were handled in #443 .

[preview]: https://dev-portal-git-zsdocs-opt-in-toast-hashicorp.vercel.app/waypoint/docs?optInFrom=waypoint-io

### CODE REVIEW

**Comment by zchsh** [comment]
This PR fixes an issue where the opt-in welcome toast on certain routes (docs routes?) would auto-dismiss immediately after rendering, resulting in an experience where the toast never really appears at all.

@BRKalow Tagged you here since I felt like the switch I made here away from `routeChangeComplete` felt a bit odd 🤔 but seems to work more reliably 🤷‍♂️ 

@ashleemboyer Tagged you here, thanks for noticing this in Slack! Let me know if this fixes things for you 🙇‍♂️

**Review by BRKalow — COMMENTED** [review]
Looks like a long-standing bug in next: https://github.com/vercel/next.js/issues/11639

I think your fix is reasonable here! Maybe leave a comment pointing at the above issue for context?

**Comment by ashleemboyer** [comment]
Taking a look now! 😊

**Review by ashleemboyer — APPROVED** [review]
Looks good to me! The toast is working as expected. 🙌🏻

🙋🏻 Any concerns with tracking `router.asPath` as-is since it can contain query parameters (`?`) and a hash (`#`)? I'm not thinking of any, but wanted to raise as a question just in case.

**Comment by zchsh** [comment]
@ashleemboyer Great question! I'm not seeing this cause issues currently (eg clicking jump links), but I've switched to `router.pathname` just in case 👍

**Pull request merged**
