### PR TITLE
[integrations] feat: adds variable group list empty state 

### PR DESCRIPTION
**Pull request by kendallstrautman**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ksadds-empty-state-integrations-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1204845103172089/1204068171740400/f) 🎟️

## 🗒️ What

Adds an empty state to variable group list integrations filtering. 

Screenshot 2023-07-11 at 4 50 34 PM
Screenshot 2023-07-11 at 4 50 30 PM

## 🛠️ How

I used the same component from the integrations library empty results. 

## 🧪 Testing

- [Visit this page](https://dev-portal-git-ksadds-empty-state-integrations-hashicorp.vercel.app/waypoint/integrations/hashicorp/aws-ssm/latest/components/config-sourcer/aws-ssm-config-sourcer), enter in a weird filter term like 'pickles'
- View the no results component
- Click 'clear' 
- validate that the query is reset
- Test again with the required checkbox filter. 

## 💭 Anything else?

We may want to adjust the messaging in the 'no results' component body for this context? @braydenlove

### CODE REVIEW

**Comment by braydenlove** [comment]
**Yeah let's go with:**
Headline: No Results
Description: Try adjusting using different keywords.

**Review by BrandonRomano — APPROVED** [review]
Love it, simple!

**Comment by kendallstrautman** [comment]
@braydenlove updated!

**Review by braydenlove — APPROVED** [review]
Thanks! 🚢

**Pull request merged**
