### PR TITLE
User auth elements polish

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🔗 Relevant links

- [Asana task](https://app.asana.com/0/1202520168081556/1202887176250192/f) 🎟️

## 🗒️ What

- Adds "sign in with..." text to `MobileUserDisclosure`
- Updates size & weight of username/email text in `MobileUserDisclosure`
- Adds border to `MobileUserDisclosure`
- Updates order, size, color, and icons of controls in `MobileAuthenticationControls`
- Adds icon to nav header "Sign In" button
- Updates size of sign up CTAs in collection and tutorial pages
- Removes `callbackUrl` overwriting in calls to `signIn`
- Updates "Sign In" button size and spacing in sign-up page
- Updates sign-up page to redirect to home page if a user is authenticated
- Fixes panel widths in sign-up page

## 🧪 Testing

- [ ] Go to the home page
- [ ] Make sure you're not signed in
- [ ] Check the sign in/up elements are correct in the nav header on wide viewports
- [ ] Check the sign in/up elements are correct in the mobile menu on narrow viewports
- [ ] Go to /sign-up
- [ ] Make sure the "Sign In" button is the right size and has the right spacing from the text it's next to
- [ ] Make sure the left and right panels each take up 50% of the page
- [ ] Go to a collection page
- [ ] Make sure the "Create an account" CTA is the right size
- [ ] Go to a tutorial page
- [ ] Make sure the "Create an account" CTA is the right size
- [ ] Click the "Sign In" button
- [ ] Make sure you are returned to the page you were on after being signed in
- [ ] Check that `MobileUserDisclosure` renders as expected in the mobile menu
- [ ] Go to /sign-up
- [ ] You should be redirected back to the home page

### CODE REVIEW

**Comment by braydenlove** [comment]
@ashleemboyer what url should we be looking at? Sorry just want to triple check!

**Comment by ashleemboyer** [comment]
> @ashleemboyer what url should we be looking at? Sorry just want to triple check!

@braydenlove it's the one given by the vercel bot! 😊 Here it is: https://dev-portal-git-ambuser-auth-polish-hashicorp.vercel.app/

**Review by braydenlove — APPROVED** [review]
Outside of the smaller HCP logo fix we are chatting about @ashleemboyer this is ready to roll! Awesome work I can't believe how fast that was!

**Review by kellyschummer — APPROVED** [review]
💯 Thank you!

**Pull request merged**
