### PR TITLE
feat: ship unified search all tab

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

This PR enables unified search in production

## 📸 Design Screenshots

Search for `well architected`

| Before | After |
| - | - | 
| waf-before | waf-after |

Search for `docker ref`

| Before | After |
| - | - | 
| docker-ref-before | docker-ref-after |

## 🧪 Testing

- Visit the [preview]
    - From the home page, open the search modal 
    - Search should look and function as expected, and match [designs]

## 💭 Anything else?

Not at the moment!

[task]: https://app.asana.com/0/1204333060736722/1204867783511187/f
[designs]: https://www.figma.com/file/O3gJUgXVTuPQn6GpjcZO9T/Search?type=design&node-id=214-12755&mode=dev
[preview]: https://dev-portal-git-zsship-unified-search-hashicorp.vercel.app/

### CODE REVIEW

**Comment by zchsh** [comment]
@braydenlove @emilypersson1 This PR ships the unified search `All` tab to production 🥳 Would love your eyes on this to check if things look good, or if there are any last changes we might need to fix up! 🙇‍♂️

**Review by braydenlove — APPROVED** [review]
I am not seeing anything, this is looking awesome.

**Review by emilypersson1 — APPROVED** [review]
very excited for this 🙏 thank you for all of your amazing work!

**Review by BRKalow — APPROVED** [review]
🚢

**Pull request merged**
