### PR TITLE
feat: certifications assembly

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Implements new Certifications pages. Specifically:

- [/certifications][/certifications]
- [/certifications/infrastructure-automation][/certifications/infrastructure-automation]
- [/certifications/networking-automation][/certifications/networking-automation]
- [/certifications/security-automation][/certifications/security-automation]

## 🛠️ How

> **Note**: This PR is an assembly branch. Work done in this PR can be examined in more detail in each of the PRs onto this assembly branch.

- https://github.com/hashicorp/dev-portal/pull/1448
- https://github.com/hashicorp/dev-portal/pull/1450
- https://github.com/hashicorp/dev-portal/pull/1452
- https://github.com/hashicorp/dev-portal/pull/1461
- https://github.com/hashicorp/dev-portal/pull/1462
- https://github.com/hashicorp/dev-portal/pull/1463
- https://github.com/hashicorp/dev-portal/pull/1467
- https://github.com/hashicorp/dev-portal/pull/1464
- https://github.com/hashicorp/dev-portal/pull/1469
- https://github.com/hashicorp/dev-portal/pull/1470
- https://github.com/hashicorp/dev-portal/pull/1472
- https://github.com/hashicorp/dev-portal/pull/1473
- https://github.com/hashicorp/dev-portal/pull/1475
- https://github.com/hashicorp/dev-portal/pull/1477
- https://github.com/hashicorp/dev-portal/pull/1478
- https://github.com/hashicorp/dev-portal/pull/1480
- https://github.com/hashicorp/dev-portal/pull/1481
- https://github.com/hashicorp/dev-portal/pull/1482
- https://github.com/hashicorp/dev-portal/pull/1485
- https://github.com/hashicorp/dev-portal/pull/1486
- https://github.com/hashicorp/dev-portal/pull/1487

## 📸 Design Screenshots

The assembly PRs listed above contain detailed design screenshots at each stage of development. The screenshots below show the work currently on this PR.

<details>
<summary>Expand for a table of screenshots</summary>

> **Note**: Pixel width columns refer to viewport widths at which the screenshot was taken.

| Page | 320px | 800px | 1920px |
| - | - | - | - |
| [/certifications][/certifications] | landing-320 | landing-800 | landing-1920 |
| [/certifications/infrastructure-automation][/certifications/infrastructure-automation] | infra-320 | infra-800 | infra-1920 |
| [/certifications/networking-automation][/certifications/networking-automation] | net-320 | net-800 | net-1920 |
| [/certifications/security-automation][/certifications/security-automation] | sec-320 | sec-800 | sec-1920 |

</details>

## 🔗 Links

- [/certifications][/certifications]
- [/certifications/infrastructure-automation][/certifications/infrastructure-automation]
- [/certifications/networking-automation][/certifications/networking-automation]
- [/certifications/security-automation][/certifications/security-automation]

## 🧪 Testing

- [ ] Visit each of the new pages listed above
    - Each page should look & function as expected, across all viewport sizes
    - Content should be as expected

## 💭 Anything else?

Not at the moment!

[task]: https://app.asana.com/0/1203301890649977/1203186539243924/f
[preview]: https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/
[/certifications]: https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications
[/certifications/infrastructure-automation]: https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications/infrastructure-automation
[/certifications/networking-automation]: https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications/networking-automation
[/certifications/security-automation]: https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications/security-automation

### CODE REVIEW

**Comment by zchsh** [comment]
@BrandonRomano @emilypersson1 @braydenlove This is the assembly PR for Certifications, should be all ready for review!`*`. To re-iterate the preview links:

- [/certifications](https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications)
- [/certifications/infrastructure-automation](https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications/infrastructure-automation)
- [/certifications/networking-automation](https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications/networking-automation)
- [/certifications/security-automation](https://dev-portal-git-zscertifications-assembly-hashicorp.vercel.app/certifications/security-automation)

---

> `*` Whoops, two final things actually, but kind of outside the new pages:
> 1. Adding the `Certifications` link in the footer
> 2. Updating the link on the home page section
> 
> I'll open PRs onto this same assembly branch with those changes shortly, but I think this PR already covers the vast majority of what we need to worry about 👍

**Comment by BrandonRomano** [comment]
@zchsh I have a silly question; beyond navigating directly, how would one discover that this page exists?  Is it the plan that we will link it on socials and expect folks to go to directly?  Or is there some merchandising somewhere I am not seeing?

**Comment by zchsh** [comment]
@BrandonRomano Great question! For a while I'd assumed we were redirecting from https://www.hashicorp.com/certification, but I don't think that's the case. We will have:
- a link in the footer
- a link from the https://developer.hashicorp.com/ home page

Apart from that I'm not sure how folks would discover this page!

**Comment by BrandonRomano** [comment]
I don't see the link in the footer / homepage -- are those to be added in the future?

**Comment by zchsh** [comment]
@BrandonRomano yep, mentioned in a kinda hidden section in [this comment](https://github.com/hashicorp/dev-portal/pull/1447#issuecomment-1358487276) & opening PRs now. Rationale was to get this PR in final design & content review for everything else, given launch timeline 👍

**Comment by BrandonRomano** [comment]
Oh got it my bad!  I should have fully read that comment 😅.  Beyond that, everything is looking good to me; I'll send along my approval here.

**Review by BrandonRomano — APPROVED** [review]
Looks good to me nice work @zchsh 🕺.

I think VQA / Content approval will be the most effective review at this point, so certainly wait for approvals from those respective folks before shipping 🚢

**Review by braydenlove — COMMENTED** [review]
@zchsh can we match the spacing between the title and the description in the accordion group to the [designs](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=16598%3A247078&t=ObLR1NPDaQ5WMNSM-1)?

**Comment by zchsh** [comment]
@braydenlove I DM'd with Kelly about that change, we settled on using "content" rather than "description", which affects the spacing and text-color of accordion content - I think the design weren't updated to match that convo though.

For context, currently [our Accordion component](https://developer.hashicorp.com/swingset/components/accordiondisclosure) supports a `description` which appears as in mockups (gray text and spaced closer to the heading), but it's always visible:

https://user-images.githubusercontent.com/4624598/208724934-f22267ba-0da6-4f00-bb4d-8137e31bc90c.mp4

**Comment by braydenlove** [comment]
Everything looks great, the only thing that isn't working is the mobile nav. I just sent you a DM about it otherwise we are good to ship.

**Comment by zchsh** [comment]
@braydenlove Great catch, ty 💖 

For posterity, there was some route-based configuration I needed to add to get the mobile menu to work on new routes 👍 I've made a follow-up task to figure out if we could avoid that pitfall in the future: 🎟️ [[discuss] mobile menu configuration on non-product pages](https://app.asana.com/0/1202097197789424/1203590087825426/f)

**Review by braydenlove — APPROVED** [review]
Awesome work @zchsh. @kellyschummer this looks really solid, take a look when you return and we can discuss anything I might have missed.

**Pull request merged**
