### PR TITLE
feat: launch revised API docs for HCP Vault Secrets

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Launches the revised OpenApiDocsView for [/hcp/api-docs/vault-secrets].

## 🛠️ How

Toggles on the associated flag to production.

## 🧪 Testing

- [ ] Visit [/hcp/api-docs/vault-secrets]
    - The page should look and function as expected, and match [design specs][figma]
    - The page should include all of the content and functionality of the [previous template][upstream/hcp/api-docs/vault-secrets]

## 💭 Anything else?

Not at the moment!

[task]: https://app.asana.com/0/1204678746647847/1205252812626137/f
[figma]: https://www.figma.com/file/wjoC3ZVsA1kDuPsFLjEFuY/API-Template?type=design&node-id=386-16727&mode=design&t=ZAZsU5CQQUG5q32N-4
[preview]: https://dev-portal-git-zsactivate-new-open-api-template-hashicorp.vercel.app/
[/hcp/api-docs/vault-secrets]: https://dev-portal-git-zsactivate-new-open-api-template-hashicorp.vercel.app/hcp/api-docs/vault-secrets
[upstream/hcp/api-docs/vault-secrets]: https://developer.hashicorp.com/hcp/api-docs/vault-secrets

### CODE REVIEW

**Comment by braydenlove** [comment]
Ignore this is you haven't merged in a fix yet! It looks like things aren't wrapping properly on mobile (near our lowest supported width). We should remove codeblocks entirely at smaller sizes but will still need to address the titles not wrapping. 
image

**Comment by zchsh** [comment]
@braydenlove ooh yeah, great catch! I've got a couple PRs in-flight that should merge soon, first one addresses the above:

- [[dev-portal#2103 - feat: better word-breaks in operation header](https://github.com/hashicorp/dev-portal/pull/2103)](https://github.com/hashicorp/dev-portal/pull/2103)
- [[dev-portal#2136 - feat: themed badges for openapi response headings](https://github.com/hashicorp/dev-portal/pull/2136#issuecomment-1686605337)](https://github.com/hashicorp/dev-portal/pull/2136#issuecomment-1686605337)

From there I think we'll pretty much be in final VQA land! ✨

**Comment by braydenlove** [comment]
@zchsh I wanted to get this on your radar. How can we mitigate titles like this? Short names? Short title with description below? 
image

**Comment by zchsh** [comment]
@braydenlove oh wow thanks for flagging, I didn't notice that!

Up till recently, we'd only ever used the `operationId` for operation titles. But the `summary` is the more correct value to use, as Kevin pointed out [here](https://hashicorp.slack.com/archives/C059X7QKWAV/p1692634295913319), so we recently updated to use `summary` and fall back to `operationId`.

Ultimately the screenshot you've flagged might be something we want to fix up in the spec file itself, rather than try to work around on the front-end, since `operation.summary` should be `A short summary of what the operation does` ([from the OpenAPI spec](https://swagger.io/specification/#operation-object)).

Alternately, we could go back to using `operationId` for now, and introduce `summary` later only once content teams feel ready for it.

Let me know what you think!

**Review by braydenlove — APPROVED** [review]
This looks great, awesome job Zach. I tested it out on a ton of devices and screen sizes and I am feeling like this is super solid. Long term it would be nice to add some sort of feedback mechanism but I know that is for tutorial content only right now so no sweat. SHIP IT

**Review by emilypersson1 — APPROVED** [review]
awesome work Zach, thanks so much!

**Review by thiskevinwang — APPROVED** [review]

**Comment by kartiklunkad26** [comment]
Looks good to me! I'll share with some of the folks as well to take a look

**Review by kartiklunkad26 — APPROVED** [review]

**Pull request merged**
