### PR TITLE
Launch HVD

### PR DESCRIPTION
**Pull request by RubenSandwich**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-rn-featsoft-launch-hvd-hashicorp.vercel.app/validated-designs) 🔎
- [HVD UAT](https://app.asana.com/0/1204908934882872/1206301725112627/f) 🎟️
- [HVD VQA](https://app.asana.com/0/1204908934882872/1206301716253445/f) 🎟️

## 🗒️ What

In order to do design reviews with folks who may be more unfamiliar with the building and running a vercel project, we are soft launching HVD content. All content is not linked to by any other source and all pages have `noindex` on them so the only way to find them is by knowing a link.

## 🧪 Testing

- [ ] [HVD loads and renders correctly](https://dev-portal-git-rn-featsoft-launch-hvd-hashicorp.vercel.app/validated-designs)
- [ ] HVD landing page and guide pages are all marked `noindex`

### CODE REVIEW

**Comment by zchsh** [comment]
👀 lurking a bit here... but I think if we set `"enable_hvd": true` in `config/preview.json`, we should see HVD pages published  on our stable staging URL at https://developer.hashicorp.services. May be an alternative to surfacing the content on the production domain!

**Comment by RubenSandwich** [comment]
> 👀 lurking a bit here... but I think if we set `"enable_hvd": true` in `config/preview.json`, we should see HVD pages published on our stable staging URL at https://developer.hashicorp.services. May be an alternative to surfacing the content on the production domain!

You can lurk @zchsh, it's all of our repo. Thank you, I did not know about that. I will move this PR over to using that and then tag you on the review.

**Review by pbortnick — APPROVED** [review]

**Comment by RubenSandwich** [comment]
@zchsh looks like it is already on: https://github.com/hashicorp/dev-portal/blob/03d4f3ff37ee6fe15f8420461c15a25e77cbf9ae/config/preview.json#L12 and [works](https://developer.hashicorp.services/validated-designs). Moving this PR to a draft, and will use it when we fully launch.

**Comment by pbortnick** [comment]
Ahh didn't see the comments until after my approval. I agree that what @zchsh suggested is good idea.

**Pull request merged**
