### PR TITLE
fix: client-side link issue on install view

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Fixes an issue on [/sentinel/install] where client-side links do not seem to function as expected. For example, the `Docs` and `Intro` links in the top navigation bar seem to fail to fully navigating, with the URL updating, but the view remaining the same.

## 🛠️ How

Refactors install page sidebar table-of-contents logic to avoid `useState` and `useEffect`. These seem to somehow be preventing the new view from rendering.

## 📸 Design Screenshots

| Before | After |
| - | - |
| before | after |

## 🧪 Testing

- [x] Visit [/sentinel/install]
    - Links in the top navigation should successfully navigate to `Intro`, `Docs`, and so on
    - Compare to [upstream][prod/sentinel/install], where links in the top nav bar do not function as expected, with the URL changing, but not the page contents

## 💭 Anything else?

This PR is largely duplicative of the work in #2276.

[task]: https://app.asana.com/0/1204759533834554/1206313101427619/f
[preview]: https://dev-portal-git-zsfixup-sentinel-install-hashicorp.vercel.app/
[/sentinel/install]: https://dev-portal-git-zsfixup-sentinel-install-hashicorp.vercel.app/sentinel/install
[prod/sentinel/install]: https://developer.hashicorp.com/sentinel/install

### CODE REVIEW

**Comment by zchsh** [comment]
@RubenSandwich There's a bit of background for this in [this PR comment](https://github.com/hashicorp/dev-portal/pull/2274#issuecomment-1854405974), and if there's any other context I can add here, happy to dive in further or sync on this 🙇‍♂️

**Review by RubenSandwich — APPROVED** [review]
Apologizes for the delay I forgot about reviewing this one yesterday. Good job also getting a refactor in as well in this PR. ❤️

**Comment by RubenSandwich** [comment]
I will be taking this PR over and merging it in today.

**Comment by pbortnick** [comment]
@RubenSandwich do we still need this PR?

**Comment by RubenSandwich** [comment]
@pbortnick yes I do, I just wanted to test it a bit more before merging.

**Comment by pbortnick** [comment]
@RubenSandwich okay sounds good! No rush, just wanted to check. Thanks!

**Comment by RubenSandwich** [comment]
@pbortnick bit considered about the scope of this PR, buuuttt here it goes. 🤞🏻

**Pull request merged**
