### PR TITLE
fix: tweak fullPath from relative href logic

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][/terraform/plugin] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Fixes an issue where some sidebar links on [/terraform/plugin][/terraform/plugin] did not function as expected.

## 🤷 Why

- We want to ensure sidebar links work as expected
- Our source `nav-data` may have relative `href` values without leading slashes
    - Example: [`plugins-nav-data.json` in `terraform-docs-common`](https://github.com/hashicorp/terraform-docs-common/blob/main/website/data/plugin-nav-data.json#L35)

## 🛠️ How

Tweaks `fullPath` construction when dealing with navNodes with relative `href` values. 

## 🧪 Testing

- [ ] Links under the `Plugin SDKs and Libraries` section of the sidebar on [/terraform/plugin][/terraform/plugin] page should work as expected
- [ ] Other non-absolute `href` links in sidebars should work as expected
    - Example: `Back to documentation` link on [/vagrant/vagrant-cloud][/vagrant/vagrant-cloud] uses non-absolute `href` ([source](https://github.com/hashicorp/vagrant/blob/main/website/data/vagrant-cloud-nav-data.json))
    - Example: many `Task Drivers / Community` links on [/nomad/docs][/nomad/docs] uses non-absolute `href` ([source](https://github.com/hashicorp/nomad/blob/main/website/data/docs-nav-data.json))

[task]: https://app.asana.com/0/1202097197789424/1202785022290157/f
[preview]: https://dev-portal-git-zsfix-terraform-sidebar-relative-hrefs-hashicorp.vercel.app
[/terraform/plugin]: https://dev-portal-git-zsfix-terraform-sidebar-relative-hrefs-hashicorp.vercel.app/terraform/plugin
[/vagrant/vagrant-cloud]: https://dev-portal-git-zsfix-terraform-sidebar-relative-hrefs-hashicorp.vercel.app/vagrant/vagrant-cloud
[/nomad/docs]: https://dev-portal-git-zsfix-terraform-sidebar-relative-hrefs-hashicorp.vercel.app/nomad/docs

### CODE REVIEW

**Comment by BRKalow** [comment]
It would be great to see some unit tests for this method, even if scoped to the specific scenarios you fixed as part of this PR!

**Comment by zchsh** [comment]
@BRKalow @ashleemboyer This PR fixes an issue with broken links in the `/terraform/plugin` sidebar.

In more detail, we previously already handled various `href` value types:
- Absolute URLs, we leave alone
- Relative URLs that start with `/<product-slug>`, we leave alone
- All other relative URLs, we assume to have been constructed for dot-io contexts, so we prefix like `/<product-slug>/{href}`

We now handle `href` values in a slightly different way, to handle some edge cases:
- Absolute URLs, we leave alone
- Relative URLs that start with `/<product-slug>/`, we leave alone
    - Note the trailing slash. This handles cases like `/vagrant-cloud`, for example.
- Relative URLs that start with `/`, we assume to have been constructed for dot-io contexts, so we prefix like `/<product-slug>/{href}`
- All other relative URLs (those that do not start with a slash), we assume to have been constructed as relative to the full current `basePath`, and prefix accordingly
    - This handles the Terraform case. On `/terraform/plugin`, given an href of `"sdkv2"`, we end up linking to `/terraform/plugin/sdkv2` as expected

Let me know what y'all think 🙇‍♂️

**Comment by zchsh** [comment]
@BRKalow ack, crossed streams there - I'll split this out and add some unit tests 👍

**Comment by BRKalow** [comment]
@zchsh To clarify, no need to adjust your implementation! Just some tests for the current method

**Comment by ashleemboyer** [comment]
> It would be great to see some unit tests for this method, even if scoped to the specific scenarios you fixed as part of this PR!

+1 to this! A few test cases will make it a little easier to visualize the goals of these changes. And since we're getting a little more complex in the logic, tests should help us maintain the behavior we want! 😊

**Comment by zchsh** [comment]
@BRKalow @ashleemboyer I've added some tests. I've split out `fullPathFromRelativeHref`, as testing expected results from `prepareNavNodeForClient` was quite verbose. Let me know if those help clarify, & seem sufficient 🙇‍♂️

**Review by BRKalow — APPROVED** [review]
👏  great tests, and I think pulling out that logic actually makes the implementation clearer. Nice job!

**Pull request merged**
