### PR TITLE
feat: add project-preview config file

### PR DESCRIPTION
**Pull request by BRKalow**
## "Ready for Review" checklist

- [ ] The Vercel preview link has been added to this PR's description
- [ ] The Asana task has been added to this PR's description
- [ ] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [ ] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [ ] The description template has been filled in below

---

## Relevant links

- [Preview link](url) 🔎
- [Asana task](url) 🎟️

## What

Adds a new `project-preview.json` config file.

## Why

This enables us to target deploy previews for separate projects, such as in hashicorp/waypoint. We'll want to do full static generation for these deployments, so using config to enable that. Those projects will set `HASHI_ENV=project-preview` and they'll be able to leverage this config file.

### CODE REVIEW

**Comment by kylemac** [comment]
@BRKalow is this supposed to be a global config or per project? the description of the PR made it seemed like the latter but the code seems like the former

**Comment by BRKalow** [comment]
@kylemac It'd be global for any other projects/repos which have preview deployments that are built from dev-portal.

**Review by dstaley — APPROVED** [review]

**Comment by dstaley** [comment]
@BRKalow I do want to callout that we're specifically checking `HASHI_ENV === 'preview'` in a few places for some functionality (primarily around redirects). Can you confirm that none of those instances are things we need to have in the project preview builds?

**Comment by BRKalow** [comment]
@dstaley Good call, yeah it looks like none of that functionality applies for deploy previews in our other projects, so this should be a-ok.

**Pull request merged**
