### PR TITLE
fix: tweak tutorials next-prev on mobile

### PR DESCRIPTION
**Pull request by zchsh**
## ✅ "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [x] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [x] The description template has been filled in below

---

## 🔗 Relevant links

- [Preview - First tutorial][first-tutorial] 🔎
- [Preview - Middle tutorial][middle-tutorial] 🔎
- [Preview - Last tutorial in middle collection][last-tutorial-in-middle-collection] 🔎
- [Preview - Last tutorial in last collection][last-tutorial-in-last-collection] 🔎
- [Preview - Single tutorial in middle collection][single-tutorial-in-middle-collection] 🔎
- [Preview - Single tutorial in last collection][single-tutorial-in-last-collection] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

This PR tweaks the mobile styling of next-previous items.

## 🤷 Why

To better match design spec.

## 🛠️ How

Switches from a grid layout to a flex layout. This layout:

- Gives individual `DirectionalLinkBox` items a `flex-basis` of `auto`, which keeps them at their content-width size and prevents them from wrapping, _unless_ space is very limited
- Allows items to wrap if needed, which means individual `DirectionalLinkBox` items will wrap to one column if space is limited with two columns. This prevents the text-wrapping we were seeing in the fixed 2-column grid layouts.
- Gives individual `DirectionalLinkBox` items a `min-width` equal to half the available space in the flex layout (not including the `gap`), which makes so that when there is sufficient space for two columns, each `DirectionalLinkBox` will occupy exactly half the space, rather than an amount of space that varies based on their content-width.

This approach is intended to optimize the number of columns based on real text content, rather than ignoring text content and switching column layouts at potentially brittle breakpoints.

## 📸 Design Screenshots

🎨 [Figma artboard link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/DevDot?node-id=7984%3A84441)

CleanShot 2022-06-01 at 12 03 53@2x

## 🧪 Testing

- [ ] Visit each of the preview links (at the top of the PR description), and confirm that the next-previous links at the bottom of the view look and function as expected

> For a more focused review, where you can review the same component code and behaviour in focused "stories", see [Storybook with identical changes](https://dev-portal-with-storybook.vercel.app/?path=/story/components-nextprevious--first-tutorial). You can navigate between stories with `⌥ + →` & `⌥ ←`. You can also compare to [a Storybook deploy before the changes were made](https://dev-portal-with-storybook-m4jg551u6-zchsh.vercel.app/?path=/story/components-nextprevious--first-tutorial).

## 💭 Anything else?

Video on rationale for `flex` layout instead of `grid` layout:

https://user-images.githubusercontent.com/4624598/171453880-817228e5-ea9e-4419-b389-d41164441435.mp4

[preview]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app
[task]: https://app.asana.com/0/1202097197789424/1202326680744335/f
[first-tutorial]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-intro
[middle-tutorial]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-install
[last-tutorial-in-middle-collection]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app/waypoint/tutorials/get-started-docker/get-started-destroy
[last-tutorial-in-last-collection]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app/vault/tutorials/tokens/token-management
[single-tutorial-in-middle-collection]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app/waypoint/tutorials/deploy-google-cloud/google-cloud-run
[single-tutorial-in-last-collection]: https://dev-portal-git-zstweak-next-prev-mobile-hashicorp.vercel.app/waypoint/tutorials/application-deployment/gitops-helm-deployment

### CODE REVIEW

**Comment by zchsh** [comment]
@kendallstrautman @braydenlove This tweaks the layout for `next-previous` to try to better match the design spec.

One caveat I forgot to mention - it's unfortunately not really feasible for to make `Next Collection` appear above `Previous` in one column, but also have `Previous` appear on the left side of `Next Collection` when then are two columns (this requires re-ordering items, which is technically possibly with `flex` layouts, but would break all the other behaviour here and generally cause confusion, both for devs and for folks using assistive tech).

CleanShot 2022-06-01 at 12 33 38@2x



cc @ashleemboyer (this is a PR that affects Learn UI ☺️)

**Review by braydenlove — APPROVED** [review]
Nice work, appreciate the explanation.

**Review by BRKalow — APPROVED** [review]
Looks good to me! The previews look great. Good use of the child selector.

**Review by ashleemboyer — APPROVED** [review]
🥇

**Review by kendallstrautman — APPROVED** [review]
💖

**Pull request merged**
