### PR TITLE
fix: remove extra toast margin

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Fixes an issue where unexpected additional margin was added to welcome toasts.

## 🤷 Why

To more closely match design spec.

## 🛠️ How

Forcefully overrides default `react-hot-toast` settings, which seemed difficult to modify through other means.

### Before

before

### After

after

## 🧪 Testing

- [ ] Visit [/waypoint/docs?optInFrom=waypoint-io][preview], and ensure the toast and its padding look as expected, on small and on larger viewports

[task]: https://app.asana.com/0/1202114367927919/1202440311005393/f
[preview]: https://dev-portal-git-zstweak-toast-spacing-hashicorp.vercel.app/waypoint/docs?optInFrom=waypoint-io

### CODE REVIEW

**Review by BRKalow — APPROVED** [review]
Seems okay, kinda nuts they have non-overridable spacing like that!

Source is here: https://github.com/timolins/react-hot-toast/blob/f981e454eb8d6c2b901ec871353ec1a52371ac39/src/components/toast-bar.tsx#L38

**Comment by zchsh** [comment]
oooh wow thanks for tracking that down @BRKalow 🙌 good to know for sure

**Comment by zchsh** [comment]
@braydenlove I'm going to merge this in, since it seems certain we want to override an unintentional `react-hot-toast` default, but definitely tag me if there are follow-up tweaks we need to make here 🙇‍♂️

**Review by braydenlove — APPROVED** [review]
Nice work!

**Pull request merged**
