### PR TITLE
[home page] Adjust hero spacing

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ambadjust-hero-spacing-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202317183612753/f) 🎟️

## 🗒️ What

- Adds a `className` prop to `VideoEmbed`
- Adjusts spacing in home page hero by breakpoint

## 🤷 Why

- The `className` prop on `VideoEmbed` makes it possible to remove the default `margin-bottom` applied to it
- The spacing on the hero was pretty large on narrower viewports

## 📸 Design Screenshots

No screenshots at the moment, just details given by Brayden in the linked ticket.

## 🧪 Testing

View the home page at the following viewport widths and ensure the new styles on `.container` and `.primary` are as expected.

- [ ] `1440px` (wide desktop)
- [ ] `1001px` (desktop)
- [ ] `729px` (tablet)
- [ ] `728px` (mobile)

### CODE REVIEW

**Comment by BRKalow** [comment]
Spacing looks much better! ✨

**Comment by braydenlove** [comment]
Dang nice work, this looks sooooo much better. Sharing with Mike to get his eyes as this is really his ticket. Will approve as soon as I hear back from him.

**Review by zchsh — APPROVED** [review]
🙌  Looks good to me!

**Comment by heitzke** [comment]
Commented in Asana but this improved the feel of top hero area greatly. Thanks for doing this

**Pull request merged**
