### PR TITLE
fix-brew-command

### PR DESCRIPTION
**Pull request by zwindler**
## 🗒️ What

Vagrant installation documentation in the website gives a wrong command

https://developer.hashicorp.com/vagrant/install?product_intent=vagrant

Running this will fail

```bash
brew install hashicorp/tap/hashicorp-vagrant
```

## 🤷 Why

Hopefully, brew gives a hint to fix the mistake

```bash
Warning: No available formula with the name "hashicorp/tap/hashicorp-vagrant". Did you mean hashicorp/tap/vagrant?
```

Running `brew install hashicorp/tap/vagrant` works

### CODE REVIEW

**Comment by zwindler** [comment]
Can anyone take a quick look at this? This is a trivial fix

**Comment by RubenSandwich** [comment]
@krastin can you confirm this update?

**Comment by RubenSandwich** [comment]
@brianshumate can we confirm this change?

**Comment by krastin** [comment]
> @krastin can you confirm this doc change?

The requested change workflow doesn't seem to work for me. Here's the _old_ version working:

```bash
% brew tap hashicorp/tap
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/bundle, warrensbox/tap and homebrew/cask).
==> New Casks
wljs-notebook

You have 75 outdated formulae and 3 outdated casks installed.
```

```bash
% brew install hashicorp/tap/hashicorp-vagrant
==> Downloading https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1_darwi
Already downloaded: /Users/krastin/Library/Caches/Homebrew/downloads/4b70740a5b8c3e37fa35305a64490aac6ab9a1a9155e877c27e82fdff65d61fc--vagrant_2.4.1_darwin_arm64.dmg
==> Installing Cask hashicorp-vagrant
==> Running installer for hashicorp-vagrant with sudo; the password may be neces
Password:
<etc, etc>
```

And the _new_ workflow failing:

```bash
% brew install hashicorp/tap/vagrant
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:307:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:238:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:527:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:527:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:751:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:964:in `factory'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:126:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:205:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:196:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting

1 %
```

Vagrant seems to be a Cask and not a Tap in the related Brew tap repo:
https://github.com/hashicorp/homebrew-tap?tab=readme-ov-file#what-packages-are-available


My system is Ventura 13.6.5 `Darwin krastin-Y6HHXYNP42 22.6.0 Darwin Kernel Version 22.6.0: Mon Feb 19 19:43:15 PST 2024; root:xnu-8796.141.3.704.6~1/RELEASE_ARM64_T8112 arm64`

I suggest we close this pull request.

**Pull request closed without merging**
