### PR TITLE
[/docs] Aligning IconTileLogo and Text with flex-start

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🗒️ What

- Updates the icon and text alignment in /docs pages

## 🤷 Why

- We'll soon have much longer text and the `flex-start` alignment looks better, as requested from design

## 🧪 Testing

Make sure the alignment looks correct on the following pages:

- [ ] [/hcp/docs](https://dev-portal-git-ambupdate-docs-hero-alignment-hashicorp.vercel.app/hcp/docs)
- [ ] [/nomad/docs](https://dev-portal-git-ambupdate-docs-hero-alignment-hashicorp.vercel.app/nomad/docs)
- [ ] [/vault/docs](https://dev-portal-git-ambupdate-docs-hero-alignment-hashicorp.vercel.app/vault/docs)
- [ ] [/waypoint/docs](https://dev-portal-git-ambupdate-docs-hero-alignment-hashicorp.vercel.app/waypoint/docs)

### CODE REVIEW

**Review by kendallstrautman — APPROVED** [review]
👏

**Comment by braydenlove** [comment]
This is awesome, thanks so much for jumping in and knocking this out :). There are a few spacing things we need to shore up that I didn't discuss in the video.

Spacing between the icon tile and the copy should be `16px` (allows us to fit a bit more content as these can get on the long side):
16px gap example
`column-gap: 16px;`

`Margin-bottom` between the `h` and `p` should be `8px` (shore up the gap tooth feeling of the current spacing up there as it feels a bit inconsistent in comparison to the others):
8px spacing between h1 and paragraph
`margin-bottom: 8px;`

Let me know if you have any questions. Other than these two items everything looks perfect, nice job.

**Comment by ashleemboyer** [comment]
@braydenlove thanks for taking a look! 💖 I've made those two updates and they're ready for review. 😊

**Comment by braydenlove** [comment]
Thanks so much. I have to walk Mike through this real quick, then I will approve!

**Review by braydenlove — APPROVED** [review]
Just caught up with Mike. This is approved, thank you so much.

**Pull request merged**
