### PR TITLE
Add Sidebar overviewItemHref prop

### PR DESCRIPTION
**Pull request by ashleemboyer**
## "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] This PR's link has been added to the "📐 Pull Request" field on the Asana task
- [x] This Vercel preview link has been added to the "🔍 Preview" field on the Asana task
- [x] The description template has been filled in below

---

## Relevant links

- [Preview link](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1202022787106807/1202105084146703/f) 🎟️

## What

- Adds a new, optional `overviewItemHref` prop to `Sidebar`

## Why

- This prop will render an "Overview" item at the top of the Sidebar `<nav>` element. Still working out the details for all pages in [[Question][Sidebar] On which Sidebars is the new Overview menu item needed? Where do they link to?](https://app.asana.com/0/1202110981600689/1202129912162121/f), but for docs pages it is intended to link to the `/{productSlug}/${basePath}` root page (where `basePath` is `docs`, `commands`, and `plugins` for Waypoint).

## How

- Started out by hardcoding the menu item to double check all the needed properties, then abstracted into a single string prop and tested usage in `src/layouts/sidebar-sidecar/server.ts`.

### Waypoint docs pages

- [ ] Go to [/waypoint](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/waypoint)
- [ ] There should not be an Overview item at the top of the Sidebar <nav>
- [ ] Go to [/waypoint/docs](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/waypoint/docs)
- [ ] There should be an Overview item at the top of the Sidebar <nav>
- [ ] The Overview item should have an active state
- [ ] The Overview item should link to `/waypoint/docs`
- [ ] Go to [/waypoint/commands](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/waypoint/commands)
- [ ] There should be an Overview item at the top of the Sidebar <nav>
- [ ] The Overview item should have an active state
- [ ] The Overview item should link to `/waypoint/commands`
- [ ] Go to [/waypoint/commands](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/waypoint/plugins)
- [ ] There should be an Overview item at the top of the Sidebar <nav>
- [ ] The Overview item should have an active state
- [ ] The Overview item should link to `/waypoint/plugins`

### Vault docs pages

- [ ] Go to [/vault](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/vault)
- [ ] There should not be an Overview item at the top of the Sidebar <nav>
- [ ] Go to [/vault/docs](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/vault/docs)
- [ ] There should be an Overview item at the top of the Sidebar <nav>
- [ ] The Overview item should have an active state
- [ ] The Overview item should link to `/vault/docs`
- [ ] Go to [/vault/api-docs](https://dev-portal-git-ambadd-sidebar-overview-prop-hashicorp.vercel.app/vault/api-docs)
- [ ] There should be an Overview item at the top of the Sidebar <nav>
- [ ] The Overview item should have an active state
- [ ] The Overview item should link to `/vault/api-docs`

## Anything else?

- `src/layouts/sidebar-sidecar/server.ts` is very docs specific, I think we probably want to consider moving that from the layout to `src/view/docs-view`
- This does not handle showing this item for Learn content yet. Still working out those details as mentioned in "Why" above, and Learn content also has its own Sidebar at the moment. Will merge them soon and then Learn content will be able to pass this prop to set the item.

### CODE REVIEW

**Comment by BRKalow** [comment]
What if someone adds an `Overview` link to the nav data and we get duplicate `Overview` links? 💭

**Comment by ashleemboyer** [comment]
> 

@BRKalow there's not a duplicate in the latest Waypoint or Vault docs, so I don't see an immediate concern yet. We can check past docs versions and remove if there is a duplicate "Overview" item added, and then I think we can add error checking for preventing a duplicate item from being added. What do you think of that? I wouldn't opt for injecting this item into the nav data since it would be more opaque like you mentioned.

**Comment by BRKalow** [comment]
Did we consider adding the `Overview` link to the nav data manually as part of the content adjustments? Or is the goal with the prop to enforce consistency?

Thinking out loud, with this new prop we're looking at:
* New code here to support the prop
* Potential content checks to ensure that we don't add an overview link to nav data at some point in the future to avoid duplicate links
* Net-new behavior of decorating the nav data with additional links
* For past versions, we would need to figure out a way to inject the correct version into the path

If we added it to the nav data manually, none of the above would be necessary, BUT we also might not get the consistent link for past versions, and there's additional manual up-front effort.

I'm sure you have given this some thought, so just trying to gain additional context here behind the decision!

**Comment by ashleemboyer** [comment]
@BRKalow moving this to Slack so we can involve more folks on the discussion more easily 😊

**Comment by ashleemboyer** [comment]
@BRKalow @kendallstrautman Cris reviewed this and approved via Slack! So this is ready for code review.

**Review by zchsh — APPROVED** [review]
✅ Given the current need for consistency and to meet design specs for Waypoint & Vault, I can see how we'd want to take this approach.

I think it'd be worth considering switching from the `overviewItemHref` props interface to an interface that allows composition of sidebar content - but that seems like a separate discussion, outside the scope of this PR as well ☺️ 

Will +1 Bryce's concerns as well on duplicate overview items - a concrete example shows up in Terraform docs occasionally, for example see <https://www.terraform.io/intro>.

I don't necessarily think that should block this PR — to me, this seems like a reasonable solution for June 20 — but I do think we may need to rethink this approach in the future; possibly pushing for the "Overview item" consistency at the content authoring level, within each product's `{basePath}-nav-data.json` file, rather than at the implementation level.

**Review by BRKalow — APPROVED** [review]
👏

**Pull request merged**
