### PR TITLE
Remove old consul associate exam from consul landing page

### PR DESCRIPTION
**Pull request by lszpunar**
A whoops fast follow to https://github.com/hashicorp/dev-portal/pull/2443

## 🔗 Relevant links

- [Preview link](https://dev-portal-git-cert-consul002-remove-moar-hashicorp.vercel.app/consul) 🔎

## 🗒️ What

Removes the card pointing to the retired exam prep materials from the consul homepage

image

## 🤷 Why

Having this card still here creates broken links when I try to remove the content the card links to
https://github.com/hashicorp/tutorials/pull/2071

## 🧪 Testing

I will view to deploy review and make sure the card is gone.

### CODE REVIEW

**Review by EnMod — APPROVED** [review]

**Comment by lszpunar** [comment]
@EnMod This PR still doesn't get rid of the retired collection in the side nav. Is there another json someplace I am unaware of.
image

**Comment by EnMod** [comment]
@lszpunar Good catch, I'll get back to you with the file to change :+1:

**Comment by EnMod** [comment]
@lszpunar The menu items on the sidebar are dynamically generated from `tutorials` collections, so removing the collection item for `002` should work, and I see you have a PR up doing just that (hashicorp/tutorials/pull/2071) :+1: 

However, _that_ PR can only be built successfully after _this_ PR merges, because hashicorp/tutorials/pull/2071 relies on the `consul/certifications` reference removed in this PR to be gone in `main` first.

That said, the menu item will be removed after the following steps are completed, in this order:
- This PR is merged.
- hashicorp/tutorials/pull/2071 is rebuilt successfully.
- hashicorp/tutorials/pull/2071 is merged.

**Comment by lszpunar** [comment]
thank you @EnMod!

**Pull request merged**
