### PR TITLE
chore: tf local preview

### PR DESCRIPTION
**Pull request by thiskevinwang**
This enables local preview via Terraform-related repositories

This looks for the `LOCAL_CONTENT_DIR` env var to be present
- ex. `LOCAL_CONTENT_DIR="../docs"`

### CODE REVIEW

**Comment by BRKalow** [comment]
@thiskevinwang do you think we should drive this via an env var defined in the scripts that are placed in each repo? 💭

**Comment by thiskevinwang** [comment]
> @thiskevinwang do you think we should drive this via an env var defined in the scripts that are placed in each repo? 💭

@BRKalow given that we currently house some other closely related configurations internally (like `navDataPrefix`), it felt appropriate to **not** use another env var

**Comment by BRKalow** [comment]
Alright, fair enough! I think the distinction here for me is that everything else is needed to correctly grab the remote content, whereas this value is only needed locally when running in the context of said repository.

**Comment by thiskevinwang** [comment]
> I think the distinction here for me is that everything else is needed to correctly grab the remote content, whereas this value is only needed locally when running in the context of said repository.

Hmm, this is a good distinction. Maybe env var **is** the approach then, to avoid cross-contaminating config responsibilities

**Review by BRKalow — APPROVED** [review]

**Pull request merged**
