### PR TITLE
style: tweak integrations tags

### PR DESCRIPTION
**Pull request by kendallstrautman**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ksstyle-integrations-filteres-hashicorp.vercel.app/vault/integrations?tiers=community&components=auth-method%2Cdatabase%2Csecrets-engine&flags=builtin%2Centerprise%2Carchived) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1203793327455180) 🎟️

## 🗒️ What

Style tweaks to the integrations filter tags as per the design spec. See the asana ticket for full context.

## 💭 Anything else?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203793327455180

### CODE REVIEW

**Review by BrandonRomano — APPROVED** [review]
Looks good from my end; I think @braydenlove's review will be good to have before merging as well.

**Review by braydenlove — COMMENTED** [review]
Hey @kendallstrautman this is great and almost perfect. Could we add 2px between the last tag and the tertiary button? right now it appears there isn't any spacing. Lmk if we need to figure out a different solution together ✌🏼.

image

**Comment by kendallstrautman** [comment]
@braydenlove that's weird! Didn't look like that locally, I'll look into it.

**Comment by kendallstrautman** [comment]
@braydenlove I can't recreate this, can you tell me how you've seen this?

**Comment by braydenlove** [comment]
> * Preview link

Very strange, all I did was decreased the width of my browser window and hovered over that tertiary button. It looks good now though...

**Review by braydenlove — APPROVED** [review]
Just re-tested all all browsers and it is looking good. Sorry about that false alarm, very odd. Thanks for the updates here, looking 💅🏼

**Pull request merged**
