### PR TITLE
refactor: add organization to URL structure

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Updates URL structures for integrations and their components to include a formatted organization slug.

The following URL structures change:
- Latest "readme" view
    - Was `/<product>/integrations/<integrationSlug>`
    - Now `/<product>/integrations/<organizationSlug>/<integrationSlug>`
    - Example: [/waypoint/integrations/BrandonRomano/aws-ami][/waypoint/integrations/BrandonRomano/aws-ami]
- Latest "component" view
    - Was `/<product>/integrations/<integrationSlug>/latest/components/<componentSlug>`
    - Now `/<product>/integrations/<organizationSlug>/<integrationSlug>/latest/components/<componentSlug>`
    - Example: [/waypoint/integrations/BrandonRomano/aws-ami/latest/components/builder][/waypoint/integrations/BrandonRomano/aws-ami/latest/components/builder]
- Versioned "readme" view
    - Was `/<product>/integrations/<integrationSlug>/<version>`
    - Now `/<product>/integrations/<organizationSlug>/<integrationSlug>/<version>`
    - Example: [/waypoint/integrations/BrandonRomano/aws-ami/0.10.4][/waypoint/integrations/BrandonRomano/aws-ami/0.10.4]
- Versioned "component" view
    - Was `/<product>/integrations/<integrationSlug>/latest/components/<componentSlug>`
    - Now `/<product>/integrations/<organizationSlug>/<integrationSlug>/latest/components/<componentSlug>`
    - Example: [/waypoint/integrations/BrandonRomano/aws-ami/0.10.4/components/builder][/waypoint/integrations/BrandonRomano/aws-ami/0.10.4/components/builder]

## 🤷 Why

Unscoped integration slugs to not feel sufficient for acting as unique identifiers for integrations. We want to include organization slugs in integration identifiers in order to identify integrations in a sufficiently unique way.

## 🛠️ How

- Add "get URL" helpers for integrations, with the new URL structure
- Restructure `src/pages` for new URLs, update `getStaticPaths` accordingly
- Fix up all links by switching to use the "get URL" helper functions

## 🧪 Testing

- [ ] Visit views at all new URLs, they should all function as expected
    - Latest "readme" view, eg [/waypoint/integrations/BrandonRomano/aws-ami][/waypoint/integrations/BrandonRomano/aws-ami]
    - Latest "component" view, eg [/waypoint/integrations/BrandonRomano/aws-ami/latest/components/builder][/waypoint/integrations/BrandonRomano/aws-ami/latest/components/builder]
    - Versioned "readme" view, eg [/waypoint/integrations/BrandonRomano/aws-ami/0.10.4][/waypoint/integrations/BrandonRomano/aws-ami/0.10.4]
    - Versioned "component" view, eg [/waypoint/integrations/BrandonRomano/aws-ami/0.10.4/components/builder][/waypoint/integrations/BrandonRomano/aws-ami/0.10.4/components/builder]
- [ ] Visit some other views that link to the above URLs, and test links
    - All links should be updated, and should now link to the correct URLs

### Note on how `formattedOrgParam` is used

In this PR, when fetching the integration, we don't actually fetch with the `organizationSlug`. Instead, after fetching the integration by its `integrationSlug` only, we compare the fetched `organizationSlug` to the requested URL parameter, and `404` if there's a mismatch.

📌 In the future, we'll likely fetch integrations using _both_ the `integrationSlug` and an `organizationSlug` derived from the `formattedOrgParam` for specificity.

[task]: https://app.asana.com/0/1202097197789424/1203822197840985/f
[preview]: https://dev-portal-git-zsadd-org-to-integration-urls-hashicorp.vercel.app
[/waypoint/integrations/BrandonRomano/aws-ami]: https://dev-portal-git-zsadd-org-to-integration-urls-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ami
[/waypoint/integrations/BrandonRomano/aws-ami/latest/components/builder]: https://dev-portal-git-zsadd-org-to-integration-urls-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ami/latest/components/builder
[/waypoint/integrations/BrandonRomano/aws-ami/0.10.4]: https://dev-portal-git-zsadd-org-to-integration-urls-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ami/0.10.4
[/waypoint/integrations/BrandonRomano/aws-ami/0.10.4/components/builder]: https://dev-portal-git-zsadd-org-to-integration-urls-hashicorp.vercel.app/waypoint/integrations/BrandonRomano/aws-ami/0.10.4/components/builder

### CODE REVIEW

**Comment by zchsh** [comment]
@BrandonRomano This PR refactors the URL structure to add in the organization name.

💭 Thought: this might be _slightly_ simpler if we omitted `@` from the URL. But I figure there's some reason we want it in the URL, so have implemented assuming we want it - easy to adjust if we want to remove it 👍

📌 Note: I've made it so we do use the URL param for now, just to check things so that URLs like [/waypoint/integrations/fakeorg/aws-ami](https://dev-portal-git-zsadd-org-to-integration-urls-hashicorp.vercel.app/waypoint/integrations/fakeorg/aws-ami) 404. I imagine in the future we won't need to this check, since we'll fetch the integration with the org slug in the identifier 👍

**Comment by kylemac** [comment]
@zchsh to stay consistent with TF Registry, i'd suggest we don't include the `@` sign

**Review by BrandonRomano — APPROVED** [review]
Looks great ✨

**Comment by BrandonRomano** [comment]
My approval still stands if it works as expected after testing!

**Pull request merged**
