### PR TITLE
Adding Consul enterprise download page

### PR DESCRIPTION
**Pull request by ashleemboyer**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ambconsul-download-enterprise-hashicorp.vercel.app/consul/downloads/enterprise) 🔎
- [Asana task](https://app.asana.com/0/1202097197789424/1202817202285215/f) 🎟️

## 🗒️ What

- Adds /consul/downloads/enterprise page

## 🤷 Why

- For parity with the page on .io: https://www.consul.io/downloads/enterprise

## 🛠️ How

- Fancy, new `isEnterpriseMode` prop on `ProductDownloadsView` (introduced in #903)

## 📸 Design Screenshots

[Figma link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Developer?node-id=12765%3A160607)

<details>
  <summary>Full screenshot</summary>
  image
</details>

## 🧪 Testing

- [ ] Go to [/consul/enterprise/downloads](https://dev-portal-git-ambconsul-download-enterprise-hashicorp.vercel.app/consul/downloads/enterprise)
- [ ] Make sure the page looks as expected based on the design

### CODE REVIEW

**Review by thiskevinwang — APPROVED** [review]
I checked out the desktop/mobile views on the deploy preview. Looks good to me!

**Review by BRKalow — APPROVED** [review]
👏

**Comment by kellyschummer** [comment]
🥰 Looking good. Thank you, Ashlee.

**Review by kellyschummer — APPROVED** [review]
👍

**Comment by ashleemboyer** [comment]
Waiting to update this branch with main until #922 and #923 are merged 😊

**Pull request merged**
