### PR TITLE
chore: upload tutorials sitemaps

### PR DESCRIPTION
**Pull request by kendallstrautman**
## 🔗 Relevant links

- [Preview link](https://dev-portal-git-ksupload-tutorials-sitemaps-hashicorp.vercel.app/) 🔎
- [Asana task](https://app.asana.com/0/1199634971449915/1203237572285308) 🎟️

### CODE REVIEW

**Review by ashleemboyer — APPROVED** [review]

**Review by mhonnatti — CHANGES_REQUESTED** [review]
each of the docs sitemaps went into the respective product folders (`./<product>-public/`). Should these go the same way? Or maybe a `./tutorials-public/` folder instead?

**Comment by kendallstrautman** [comment]
@mhonnatti I see all the docs ones in the same root directory. I could be wrong but, perhaps those folders are for the proxied-io-sites?

**Comment by kendallstrautman** [comment]
@mhonnatti I moved them to a `tutorials-sitemap` dir

**Review by mhonnatti — APPROVED** [review]

**Comment by mhonnatti** [comment]
Thanks for the update! I suspect you're right about sitemaps in dirs, but still good to keep tutorials sitemaps contained in their own dir. I'll merge this now and have the tutorials sitemaps submitted to Google

**Pull request merged**
