### PR TITLE
refactor: reduce tutorial page file boilerplate

### PR DESCRIPTION
**Pull request by zchsh**
## 🔗 Relevant links

- [Preview link][preview] 🔎
- [Asana task][task] 🎟️

## 🗒️ What

Minor refactor to some `tutorial-view` related code to reduce boilerplate in `src/page` files.

## 🤷 Why

To make it slightly easier to add tutorial routes for additional products.

## 🛠️ How

- renames `layout` prop to `layoutProps` to allow direct export of `TutorialView`
- sets up `generateStaticFunctions` in `tutorial-view/server` to reduce related boilerplate

## 🧪 Testing

- [ ] Visit a Vault tutorial page, such as [/vault/tutorials/getting-started/getting-started-dev-server][/vault/tutorials/getting-started/getting-started-dev-server], and ensure it renders as expected
- [ ] Visit a Waypoint tutorial page, such as [/waypoint/tutorials/deploy-aws/aws-lambda][/waypoint/tutorials/deploy-aws/aws-lambda], and ensure it renders as expected

[task]: https://app.asana.com/0/1202097197789424/1202591099445219/f
[preview]: https://dev-portal-git-zsreduce-tutorial-boilerplate-hashicorp.vercel.app
[/vault/tutorials/getting-started/getting-started-dev-server]: https://dev-portal-git-zsreduce-tutorial-boilerplate-hashicorp.vercel.app/vault/tutorials/getting-started/getting-started-dev-server
[/waypoint/tutorials/deploy-aws/aws-lambda]: https://dev-portal-git-zsreduce-tutorial-boilerplate-hashicorp.vercel.app/waypoint/tutorials/deploy-aws/aws-lambda

### CODE REVIEW

**Comment by zchsh** [comment]
@kendallstrautman This is a bit of a silly PR, but figured it could make sense to try to minimize boilerplate needed in `src/page` files for `[...tutorialSlug]` routes as we add more products. Thinking I'll try the same for `[collectionSlug]` routes.

Let me know what you think! 🙇‍♂️

**Comment by zchsh** [comment]
@ashleemboyer This is one PR kind of picked out of #686 - aim being to make it easier to add Nomad (and further product) tutorial routes.

**Comment by ashleemboyer** [comment]
Taking a look now 😊

**Review by ashleemboyer — APPROVED** [review]
Looks good! This should be a solid DX improvement ✨

**Pull request merged**
