### PR TITLE
fix: address MDX render issues

### PR DESCRIPTION
**Pull request by zchsh**
## ✅ "Ready for Review" checklist

- [x] The Vercel preview link has been added to this PR's description
- [x] The Asana task has been added to this PR's description
- [x] The description template has been filled in below

---

## 🔗 Relevant links

- 🔎 [Preview - /waypoint/tutorials/deploy-aws/aws-lambda][/waypoint/tutorials/deploy-aws/aws-lambda] 
- 🔎 [Preview - /vault/tutorials/secrets-management/multi-factor-authentication][/vault/tutorials/secrets-management/multi-factor-authentication]
- 🎟️ [[Tutorial Content] Codeblock, tabs bug with image border](https://app.asana.com/0/1202001387788447/1202286147442117/f)
- 🎟️ [[Tutorial Content] Alert renders dark like a codeblock?](https://app.asana.com/0/1202001387788447/1202286147442119/f)
- 🎟️ [Tabs rendering in an image container for some reason](https://app.asana.com/0/1202097197789424/1202221422987978/f)

## 🗒️ What

Fixes an issue where the MDX custom `img` component seems to cause a variety of hydration mismatch issues.

## 🛠️ How

- Replaces a `div` with a `span`

## 🧪 Testing

- Visit [/waypoint/tutorials/deploy-aws/aws-lambda][/waypoint/tutorials/deploy-aws/aws-lambda], and ensure the page looks as expected
    - The code block at the start of the `Update lambda function` section should look like a code block, not an image
    - The blue alert component at the end of the `Update lamba function` section should look like a blue alert box, not a code block
- Visit [/vault/tutorials/secrets-management/multi-factor-authentication][/vault/tutorials/secrets-management/multi-factor-authentication]
    - The tabs near the start of the `Scenario tasks` section should render as expected (previously they rendered into an image container)

## 💭 Anything else?

I think (hope!) this fix may solve a number of MDX rendering issues we've seen throughout `/tutorials` routes - and possibly in `/docs` routes as well. 

[/waypoint/tutorials/deploy-aws/aws-lambda]: https://dev-portal-git-zsaddress-mdx-render-issues-hashicorp.vercel.app/waypoint/tutorials/deploy-aws/aws-lambda
[/vault/tutorials/secrets-management/multi-factor-authentication]: https://dev-portal-git-zsaddress-mdx-render-issues-hashicorp.vercel.app/vault/tutorials/secrets-management/multi-factor-authentication

### CODE REVIEW

**Comment by zchsh** [comment]
@kendallstrautman This PR fixes a few (maybe all?) of the weird "why is this happening" MDX things we were seeing (code blocks and tabs in image containers; alerts that look like code blocks; etc).

Let me know if the fixes look okay! It's a weird one, I'm still not _exactly_ sure why this works - I think it has to do with HTML validity? 🤷‍♂️

**Comment by BRKalow** [comment]
@zchsh Are there any console warnings in dev before you made this change related to hydration?

**Comment by zchsh** [comment]
@BRKalow Indeed there are! Seems like it's `react-dom` doing the validation and finding things to be messed up? This is new to me, but makes sense I suppose 👍

<details>

<summary>Screenshot of console in dev</summary>

CleanShot 2022-05-24 at 20 48 19@2x

</details>

**Review by BRKalow — APPROVED** [review]

**Review by kendallstrautman — APPROVED** [review]
🎱 🙇‍♀️ ✨

**Pull request merged**
